<?php

namespace ContainerFRZn7ua;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JttmJVcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JttmJVc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JttmJVc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'feedbackRepo' => ['privates', 'App\\Repository\\FeedbackRepository', 'getFeedbackRepositoryService', true],
        ], [
            'feedbackRepo' => 'App\\Repository\\FeedbackRepository',
        ]);
    }
}
