<?php

namespace ContainerFRZn7ua;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MUB_46NService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MUB.46N' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'authenticator' => ['privates', '.errored..service_locator.MUB.46N.Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator', NULL, 'Cannot autowire service ".service_locator.MUB.46N": it references class "Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator" but no such service exists. You should maybe alias this class to the existing "security.authenticator.form_login.main" service.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'userAuthenticator' => ['privates', 'security.user_authenticator', 'getSecurity_UserAuthenticatorService', true],
            'utilisateurRepository' => ['privates', 'App\\Repository\\UtilisateurRepository', 'getUtilisateurRepositoryService', true],
        ], [
            'authenticator' => 'Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator',
            'entityManager' => '?',
            'userAuthenticator' => '?',
            'utilisateurRepository' => 'App\\Repository\\UtilisateurRepository',
        ]);

        if (isset($container->privates['.service_locator.MUB.46N'])) {
            return $container->privates['.service_locator.MUB.46N'];
        }

        return $container->privates['.service_locator.MUB.46N'] = $instance;
    }
}
