<?php

namespace ContainerFRZn7ua;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFormLoginAuthenticatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.MUB.46N.Symfony\Component\Security\Http\Authenticator\FormLoginAuthenticator' shared service.
     *
     * @return \Symfony\Component\Security\Http\Authenticator\FormLoginAuthenticator
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.MUB.46N": it references class "Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator" but no such service exists. You should maybe alias this class to the existing "security.authenticator.form_login.main" service.');
    }
}
