<?php

namespace ContainerFRZn7ua;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoadDemoDataCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\LoadDemoDataCommand' shared autowired service.
     *
     * @return \App\Command\LoadDemoDataCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'LoadDemoDataCommand.php';

        $container->privates['App\\Command\\LoadDemoDataCommand'] = $instance = new \App\Command\LoadDemoDataCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setName('app:load-demo-data');
        $instance->setDescription('Loads demo data into the database');

        return $instance;
    }
}
