<?php

namespace ContainerFRZn7ua;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTacheService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Entity\Tache' shared autowired service.
     *
     * @return \App\Entity\Tache
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Entity'.\DIRECTORY_SEPARATOR.'Tache.php';

        return $container->privates['App\\Entity\\Tache'] = new \App\Entity\Tache();
    }
}
