<?php

namespace ContainerKexC9Go;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_98AlCexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.98AlCex' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.98AlCex'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'bilanSanteRepository' => ['privates', 'App\\Repository\\BilanSanteRepository', 'getBilanSanteRepositoryService', true],
            'budgetRepository' => ['privates', 'App\\Repository\\BudgetRepository', 'getBudgetRepositoryService', true],
            'depenseRepository' => ['privates', 'App\\Repository\\DepenseRepository', 'getDepenseRepositoryService', true],
            'objectifRepository' => ['privates', 'App\\Repository\\ObjectifRepository', 'getObjectifRepositoryService', true],
            'planningRepository' => ['privates', 'App\\Repository\\PlanningRepository', 'getPlanningRepositoryService', true],
            'tacheRepository' => ['privates', 'App\\Repository\\TacheRepository', 'getTacheRepositoryService', true],
        ], [
            'bilanSanteRepository' => 'App\\Repository\\BilanSanteRepository',
            'budgetRepository' => 'App\\Repository\\BudgetRepository',
            'depenseRepository' => 'App\\Repository\\DepenseRepository',
            'objectifRepository' => 'App\\Repository\\ObjectifRepository',
            'planningRepository' => 'App\\Repository\\PlanningRepository',
            'tacheRepository' => 'App\\Repository\\TacheRepository',
        ]);
    }
}
