<?php

namespace ContainerKexC9Go;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ufl8yzXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ufl8yzX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ufl8yzX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'bilanSanteRepository' => ['privates', 'App\\Repository\\BilanSanteRepository', 'getBilanSanteRepositoryService', true],
            'suiviSanteRepository' => ['privates', 'App\\Repository\\SuiviSanteRepository', 'getSuiviSanteRepositoryService', true],
        ], [
            'bilanSanteRepository' => 'App\\Repository\\BilanSanteRepository',
            'suiviSanteRepository' => 'App\\Repository\\SuiviSanteRepository',
        ]);
    }
}
