<?php

namespace ContainerKexC9Go;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Vy0HKmCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vy0HKmC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'budgetRepository' => ['privates', 'App\\Repository\\BudgetRepository', 'getBudgetRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'budgetRepository' => 'App\\Repository\\BudgetRepository',
            'entityManager' => '?',
        ]);

        if (isset($container->privates['.service_locator.vy0HKmC'])) {
            return $container->privates['.service_locator.vy0HKmC'];
        }

        return $container->privates['.service_locator.vy0HKmC'] = $instance;
    }
}
