<?php

namespace ContainerKexC9Go;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getObjectifService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Entity\Objectif' shared autowired service.
     *
     * @return \App\Entity\Objectif
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Entity'.\DIRECTORY_SEPARATOR.'Objectif.php';

        return $container->privates['App\\Entity\\Objectif'] = new \App\Entity\Objectif();
    }
}
