<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Utilisateur extends \App\Entity\Utilisateur implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'age' => [parent::class, 'age', null, 16],
        "\0".parent::class."\0".'ban_until' => [parent::class, 'ban_until', null, 16],
        "\0".parent::class."\0".'bilanSantes' => [parent::class, 'bilanSantes', null, 16],
        "\0".parent::class."\0".'budgets' => [parent::class, 'budgets', null, 16],
        "\0".parent::class."\0".'created_at' => [parent::class, 'created_at', null, 16],
        "\0".parent::class."\0".'depenses' => [parent::class, 'depenses', null, 16],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null, 16],
        "\0".parent::class."\0".'empreinte_faciale' => [parent::class, 'empreinte_faciale', null, 16],
        "\0".parent::class."\0".'facebookId' => [parent::class, 'facebookId', null, 16],
        "\0".parent::class."\0".'feedbacks' => [parent::class, 'feedbacks', null, 16],
        "\0".parent::class."\0".'githubId' => [parent::class, 'githubId', null, 16],
        "\0".parent::class."\0".'googleId' => [parent::class, 'googleId', null, 16],
        "\0".parent::class."\0".'hasSetPassword' => [parent::class, 'hasSetPassword', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'isVerified' => [parent::class, 'isVerified', null, 16],
        "\0".parent::class."\0".'mot_de_passe' => [parent::class, 'mot_de_passe', null, 16],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null, 16],
        "\0".parent::class."\0".'objectifs' => [parent::class, 'objectifs', null, 16],
        "\0".parent::class."\0".'photo' => [parent::class, 'photo', null, 16],
        "\0".parent::class."\0".'plannings' => [parent::class, 'plannings', null, 16],
        "\0".parent::class."\0".'prenom' => [parent::class, 'prenom', null, 16],
        "\0".parent::class."\0".'role' => [parent::class, 'role', null, 16],
        "\0".parent::class."\0".'suiviSantes' => [parent::class, 'suiviSantes', null, 16],
        "\0".parent::class."\0".'taches' => [parent::class, 'taches', null, 16],
        "\0".parent::class."\0".'taskSpaces' => [parent::class, 'taskSpaces', null, 16],
        "\0".parent::class."\0".'telephone' => [parent::class, 'telephone', null, 16],
        "\0".parent::class."\0".'verificationCode' => [parent::class, 'verificationCode', null, 16],
        "\0".parent::class."\0".'verificationCodeExpiresAt' => [parent::class, 'verificationCodeExpiresAt', null, 16],
        'age' => [parent::class, 'age', null, 16],
        'ban_until' => [parent::class, 'ban_until', null, 16],
        'bilanSantes' => [parent::class, 'bilanSantes', null, 16],
        'budgets' => [parent::class, 'budgets', null, 16],
        'created_at' => [parent::class, 'created_at', null, 16],
        'depenses' => [parent::class, 'depenses', null, 16],
        'email' => [parent::class, 'email', null, 16],
        'empreinte_faciale' => [parent::class, 'empreinte_faciale', null, 16],
        'facebookId' => [parent::class, 'facebookId', null, 16],
        'feedbacks' => [parent::class, 'feedbacks', null, 16],
        'githubId' => [parent::class, 'githubId', null, 16],
        'googleId' => [parent::class, 'googleId', null, 16],
        'hasSetPassword' => [parent::class, 'hasSetPassword', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'isVerified' => [parent::class, 'isVerified', null, 16],
        'mot_de_passe' => [parent::class, 'mot_de_passe', null, 16],
        'nom' => [parent::class, 'nom', null, 16],
        'objectifs' => [parent::class, 'objectifs', null, 16],
        'photo' => [parent::class, 'photo', null, 16],
        'plannings' => [parent::class, 'plannings', null, 16],
        'prenom' => [parent::class, 'prenom', null, 16],
        'role' => [parent::class, 'role', null, 16],
        'suiviSantes' => [parent::class, 'suiviSantes', null, 16],
        'taches' => [parent::class, 'taches', null, 16],
        'taskSpaces' => [parent::class, 'taskSpaces', null, 16],
        'telephone' => [parent::class, 'telephone', null, 16],
        'verificationCode' => [parent::class, 'verificationCode', null, 16],
        'verificationCodeExpiresAt' => [parent::class, 'verificationCodeExpiresAt', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
