<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKexC9Go\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKexC9Go/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKexC9Go.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKexC9Go\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKexC9Go\App_KernelDevDebugContainer([
    'container.build_hash' => 'KexC9Go',
    'container.build_id' => '5ec81530',
    'container.build_time' => 1771801150,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKexC9Go');
